openapi: 3.0.0
info:
  title: Game Data API
  version: "1.0.0"
  description: "API for retrieving random game data with keys: title, description, price, and date_released."

servers:
  - url: https://task-maker-vc02.onrender.com/
    description: Development server

paths:
  /games:
    get:
      summary: "Get a list of games"
      description: "Returns a list of games with random data."
      responses:
        "200":
          description: "Successful response with a list of game objects."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      example: "Adventure Quest"
                    description:
                      type: string
                      example: "An exciting journey awaits you in this thrilling adventure game."
                    price:
                      type: number
                      format: float
                      example: 29.99
                    date_released:
                      type: string
                      format: date
                      example: "2021-05-15"
components:
  schemas:
    Game:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        date_released:
          type: string
          format: date
